### ISSUE TITLE
cipm pulls pacote@7 into npm, along with stream write-after-end heisenbug

### ISSUE THREAD

**Issue by JensEggers** [zkat/cipm#52]
npm itself now uses pacote@8, which has this fix (https://github.com/zkat/pacote/pull/151), but I still sometimes encounter https://github.com/zkat/pacote/issues/142 using npm@6.1.0 with Node 6.13.1 on macOS. The reason appears to be that cipm still has the old pacote dependency.

**Comment by JensEggers** [comment]
The bug is hard to reproduce but seems to happen most often when using ```npm ci``` on a slightly flaky mobile internet link.

**Comment by JensEggers** [comment]
Here's a representative error log, obtained while running ```npm ci``` in a repo with private dependencies. npm hangs indefinitely after the last error.
```
✘-1 ~/git/fst_bridge [master|✔] 

09:16 $ npm ci

npm WARN prepare removing existing node_modules/ before installation

events.js:160░░░░░░⸩ ⠇ extractTree: sill extractTree minimist@0.0.8 -> /Users/jens/git/fst_bridge/node_modules/minimist

      throw er; // Unhandled 'error' event

      ^



Error: write after end

    at writeAfterEnd (_stream_writable.js:195:12)

    at PassThrough.Writable.write (_stream_writable.js:242:5)

    at PassThrough.Writable.end (_stream_writable.js:480:10)

    at ReadEntry.entry.on (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/libcipm/node_modules/pacote/lib/extract-stream.js:19:41)

    at emitOne (events.js:101:20)

    at ReadEntry.emit (events.js:188:7)

    at ReadEntry.emit (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)

    at ReadEntry.[maybeEmitEnd] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:252:12)

    at ReadEntry.end (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:165:27)

    at Unpack.[consumeBody] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)

    at Unpack.[consumeChunkSub] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)

    at Unpack.[consumeChunk] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)

    at Unzip.(anonymous function).on.chunk (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)

    at emitOne (events.js:96:13)

    at Unzip.emit (events.js:188:7)

    at Unzip.emit (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)

events.js:160     ░⸩ ⠙ extractTree: sill extractTree unc-path-regex@0.1.2 -> /Users/jens/git/fst_bridge/node_modules/unc-path-regex

      throw er; // Unhandled 'error' event

      ^



Error: write after end

    at writeAfterEnd (_stream_writable.js:195:12)

    at PassThrough.Writable.write (_stream_writable.js:242:5)

    at PassThrough.Writable.end (_stream_writable.js:480:10)

    at ReadEntry.entry.on (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/libcipm/node_modules/pacote/lib/extract-stream.js:19:41)

    at emitOne (events.js:101:20)

    at ReadEntry.emit (events.js:188:7)

    at ReadEntry.emit (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)

    at ReadEntry.[maybeEmitEnd] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:252:12)

    at ReadEntry.end (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:165:27)

    at Unpack.[consumeBody] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)

    at Unpack.[consumeChunkSub] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)

    at Unpack.[consumeChunk] (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)

    at Unzip.(anonymous function).on.chunk (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)

    at emitOne (events.js:96:13)

    at Unzip.emit (events.js:188:7)

    at Unzip.emit (/Users/jens/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)

npm ERR! cancel after 1 retries!
```

**Comment by JensEggers** [comment]
just noticed this is already fixed, closing
